### PR TITLE
Add pagination to Artifacts methods

### PR DESCRIPTION
**Pull request by EnricoMi**

### CODE REVIEW

**Review by pyasi — APPROVED** [review]

**Comment by EnricoMi** [comment]
@pyasi when is the next release scheduled?

**Comment by pyasi** [comment]
@EnricoMi it's quite easy. I'll release a patch so that this is live.

**Comment by EnricoMi** [comment]
Sorry, I mean this comment to go into #58. I think this PR has been released with v1.1.0 already.

**Comment by EnricoMi** [comment]
I can confirm v1.1.1 contains what I need, thanks for the quick release!

**Pull request merged**
